name: build-snapshot

on:
  workflow_dispatch:
  push:
    paths:
    - 'components/**'
    - 'plugins/**'
    - 'sdk/**'
    - 'src/**'
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - name: Install Lazarus
      uses: doublecmd/lazarus-install@win
      with:
        lazarus-version: "stable"

    - name: Checkout source
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Build packages
      run: ./.github/scripts/create_snapshot.bat

    - name: Save revision number
      run: echo "REVISION=$(git rev-list --count HEAD)" >> "$GITHUB_ENV"
      shell: bash 

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: alexx2000/snapshots
        repo_token: ${{ secrets.SNAPSHOTS }}
        file: doublecmd-release/doublecmd*.7z
        release_name: Revision ${{ env.REVISION }}
        tag: ${{ env.REVISION }}
        overwrite: true
        file_glob: true
        body: "Go to the [Double Commander download page](https://sourceforge.net/p/doublecmd/wiki/Download) to download the latest release."


