name: build-snapshot

on:
  workflow_dispatch:
  push:
    paths:
    - 'components/**'
    - 'plugins/**'
    - 'sdk/**'
    - 'src/**'
    branches:
      - master

env:
  # Setting an environment variable with the value of a configuration variable
  BODY: ${{ vars.REPOSITORY_BODY }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-win:
    runs-on: windows-latest
    environment:
      name: BODY
    steps:
    - name: Checkout source
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: List all available environment variables 1
      run: env

    - name: List all available environment variables 2
      run: vars


    - name: Save revision number
      run: echo "REVISION=$(git rev-list --count HEAD)" >> "$GITHUB_ENV"
      shell: bash 

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: alexx2000/snapshots
        repo_token: ${{ secrets.SNAPSHOTS }}
        file: doublecmd-release/doublecmd*.7z
        release_name: Revision ${{ env.REVISION }}
        tag: ${{ env.REVISION }}
        body: ${{ vars.BODY }}
        overwrite: true
        file_glob: true











