name: build-snapshot

on:
  workflow_dispatch:
  push:
    paths:
    - 'components/**'
    - 'plugins/**'
    - 'sdk/**'
    - 'src/**'
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BODY: |
    **These snapshots are generated automatically and are untested.**
          
    **Linux (repositories)**
    [doublecmd-qt-latest](https://software.opensuse.org//download.html?project=home%3AAlexx2000%3Adoublecmd-svn&package=doublecmd-qt)
    [doublecmd-gtk-latest](https://software.opensuse.org//download.html?project=home%3AAlexx2000%3Adoublecmd-svn&package=doublecmd-gtk)
          
    **Linux 64 bit (AppImage)**
    [doublecmd-qt-latest-x86_64.AppImage](https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/AppImage/doublecmd-qt-latest-x86_64.AppImage)          
    [doublecmd-gtk-latest-x86_64.AppImage](https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/AppImage/doublecmd-gtk-latest-x86_64.AppImage)

    **Microsoft Windows 32/64 bit  macOS >= 11**  

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - name: Install Lazarus
      uses: doublecmd/lazarus-install@win
      with:
        lazarus-version: "stable"

    - name: Checkout source
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Build packages
      run: ./.github/scripts/create_snapshot.bat

    - name: Save revision number
      run: echo "REVISION=$(git rev-list --count HEAD)" >> "$GITHUB_ENV"
      shell: bash 

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: alexx2000/snapshots
        repo_token: ${{ secrets.SNAPSHOTS }}
        file: doublecmd-release/doublecmd*.7z
        release_name: Revision ${{ env.REVISION }}
        tag: ${{ env.REVISION }}
        body: ${{ env.BODY }}
        overwrite: true
        file_glob: true
